minor tweaks and types

diff --git a/bin/getdata b/bin/getdata
--- a/bin/getdata
+++ b/bin/getdata
@@ -1,20 +1,24 @@
 #!/usr/bin/env zsh
 
-OPTSTRING=":rsm"
+OPTSTRING=":o:rsm"
 
 # check for the optional rerun flag and set it to false by default
 # if the flag is set, set it to true
 # the rerun flag is the only optional flag and is the final argument
 RERUN=0
 NOGUI=0
-USE8M=0
+LAST=0
 while getopts ${OPTSTRING} arg; do
     case ${arg} in
         r) RERUN=1 ;;
         s) NOGUI=1 ;;
-        m) USE8M=1 ;;
+        o) ALTOPS=$OPTARG ;;
+        l) LAST=1 ;;
         \?)
           echo "Invalid option: -$OPTARG" 1>&2
+          exit 1 ;;
+        :)
+          echo "Option -$OPTARG requires an argument." 1>&2
           exit 1 ;;
     esac
 done
@@ -22,17 +26,33 @@ done
 #shift away the parsed options to access the positional arguments
 shift $((OPTIND -1))
 
+# look for last experiment if flag is set
+if [[ $LAST -eq 1 ]] || [[ $# -eq 0 ]]; then
+    # get the last experiment
+    LASTDATE=$(ls /mnt/servers/frankenshare/Will/ScanImage\ Data | tail -n 1)
+    LASTEXP=$(ls /mnt/servers/frankenshare/Will/ScanImage\ Data/$LASTDATE | tail -n 1)
+    echo "Last experiment: $LASTEXP/$LASTDATE"
+    read -q "confirm?Are you sure you want to proceed? (y/n) "
+    echo ""
+
+    if [[ $confirm != [Yy] ]]; then
+        echo "Aborted."
+        exit 1
+    fi
+    # set the positional arguments to the last experiment
+    set -- $LASTEXP $LASTDATE
+fi
 
 # begin processing pipeline
 eval "$(conda shell.zsh hook)"
 
-if [ $NOGUI -eq 1 ]; then
+if [[ $NOGUI -eq 1 ]]; then
     echo "Running in silent/no-gui mode..."
 fi
 
 # check if rerun flag is set
 # if so, skip the first two steps
-if [ $RERUN -eq 1 ]; then
+if [[ $RERUN -eq 1 ]]; then
     echo "Running suite2p only..."
 else
     # move files
@@ -49,15 +69,16 @@ fi
 
 # run suite2p
 conda activate suite2p
-if [ $USE8M -eq 1 ]; then
-    echo "Running suite2p with gcamp8m ops..."
-    s2p_cli $1 $2 --ops ops_8m
+if [[ -n $ALTOPS ]]; then
+    echo "Running suite2p with user specified ops: $ALTOPS..."
+    s2p_cli $1 $2 --ops $ALTOPS
 else
     echo "Running suite2p..."
     s2p_cli $1 $2
 fi
 
-if [ $NOGUI -eq 1 ]; then
+# default behavior is to open suite2p gui and file explorer
+if [[ $NOGUI -eq 1 ]]; then
     conda deactivate
     exit 0
 else
